name: Ubuntu - build editor

on:
  push:
    paths:
      - .github/workflows/build-editor-ubuntu.yml
      - .gitmodules
      - config/**
      - external/**
      - src/**
      - editor/**
      - scripts/**
      - CMakeLists.txt
      - CMakePresets.json
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
    env:
      BUILD_TYPE: ${{matrix.build_type}}

    steps:
    - name: Checkout code with lfs
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build/editor

    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf
        git@github.com:

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Update deb repo links
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install qtbase5-dev

    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 13
        platform: x64

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Generate project
      shell: bash
      working-directory: ${{github.workspace}}/build/editor
      env:
        CC: gcc-13
        CXX: g++-13
      run: cmake ${{github.workspace}}/editor -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build/editor
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

